name: GitHub Profile Summary Cards

on:
  schedule: # Executa a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite executar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_CARDS_TOKEN }} # Token pessoal para acesso completo
        with:
          USERNAME: ${{ github.repository_owner }} # Seu username (FaBrCh)
          BRANCH_NAME: "main" # Branch onde os cards serão salvos
          UTC_OFFSET: -3 # Fuso horário do Brasil (UTC-3)
          EXCLUDE: "" # Linguagens para excluir (deixe vazio)
          AUTO_PUSH: true # Faz commit automático dos cards 